apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobot-deployment
  namespace: gobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobot-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gobot-app
    spec:
      containers:
        - name: gobot
          image: squadassistcontainerregistry.azurecr.io/gobot:#{Release.Artifacts.GoBot.BuildId}#
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 50m
          env:
            - name: BUILD_VERSION
              value: "#{Release.Artifacts.GoBot.BuildId}#"
            - name: MONGO_URI
              value: "mongodb://mongodb.mongodb.gobot.svc.cluster.local:27017"
      dnsConfig:
        options:
          - name: single-request-reopen
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: squadassistregistrykey
